### ISSUE TITLE
Feature request: Flatten event metadata into the json

### ISSUE THREAD

**Issue by RyanAD** [open-schnick/DatadogFormattingLayer#8]
Currently event metadata is put into the log message like `field=value`, it would be nice to have something similar to [tracing_subscriber's flatten](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/format/struct.Json.html#method.flatten_event) so that the metadata is sent as part of the JSON and can then be used with Datadog's filtering.

If this is something that would be accepted as a PR, I can work on this in 3-4 weeks.

**Comment by open-schnick** [comment]
Hi,
i think that's a great idea and should be easy to implement.
Would you put the key-value-pairs in the top level of the json or in some form of nested structure?
I think both ways to enable us to filter by the key.

**Comment by open-schnick** [comment]
I added it into version 2.2.0
